### PR TITLE
add deletecollection verb

### PR DESCRIPTION
**Pull request by kimxogus**
This caused in `patronictl remove`

- reference: https://github.com/zalando/patroni/pull/1033

```plain
2019-06-18 02:29:14,992 - ERROR - Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 61, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 393, in delete_cluster
    self.retry(self._api.delete_collection_namespaced_kind, self._namespace, label_selector=self._label_selector)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 113, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 254, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 50, in wrapper
    return getattr(self._api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 7373, in delete_collection_namespaced_endpoints
    (data) = self.delete_collection_namespaced_endpoints_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 7476, in delete_collection_namespaced_endpoints_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 387, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 256, in DELETE
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 18 Jun 2019 02:29:14 GMT', 'Content-Length': '321'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints is forbidden: User \"system:serviceaccount:namespace:zalando-postgres-operator\" cannot deletecollection resource \"endpoints\" in API group \"\" in the namespace \"beta\"","reason":"Forbidden","details":{"kind":"endpoints"},"code":403}
```

### CODE REVIEW

**Comment by FxKu** [comment]
Thanks @kimxogus. Could you add a short command that this is needed for `patronictl remove`? Just behind the verb. Please, also introduce the verb in the [example](https://github.com/zalando/postgres-operator/blob/master/manifests/operator-service-account-rbac.yaml) manifest for RBAC.

**Comment by kimxogus** [comment]
@FxKu I needed to run `patronictl remove` because

1. Postgres Cluster pod with `registry.opensource.zalan.do/acid/spilo-cdp-10:1.5-p35` and postgres version `9.6` suddenly failed with log something like `failed to start postgres`(no logs are remained. sorry).
2. I tried many workarounds like below, but nothing worked.
    - recreate pod
    - delete pvc and recreate pod
    - delete pvc, delete wale backup in s3 storage and recreate pod
3. So I tried to recreate postgresql cluster by `kubectl delete -f manifest.yaml` and `kubectl apply -f manifest.yaml`.
4. Now https://github.com/zalando/patroni/issues/937 occurred.
5. I needed to run `patronictl remove` in postgresql pod and recreate cluster.
6. With `deletecollection` verb, `patronictl remove` worked and resolved the issue.

**Comment by kimxogus** [comment]
Also I want operator to make sure a cluster is removed.

https://github.com/zalando/patroni/issues/937#issuecomment-456019883

**Comment by FxKu** [comment]
I think `patronictl reinit` could have helped as well. Did you also try that?
Aside from that I have no objections against introducing another verb.

**Comment by FxKu** [comment]
:+1:

**Comment by kimxogus** [comment]
> I think `patronictl reinit` could have helped as well. Did you also try that?
> Aside from that I have no objections against introducing another verb.

`patronictl reinit` seems much more handy! Thanks. I'll try that when I encounter initialization problem.

**Comment by Jan-M** [comment]
:+1:

**Pull request merged**
