### PR TITLE
WIP: some code refactoring about controller.go

### PR DESCRIPTION
**Pull request by zvier**
* no logic change, only for clean code
* reduce if-else nested for it looks more clean

### CODE REVIEW

**Comment by zvier** [comment]
Hello, I'm new and interest for this project, start with some small optimizations for it. Thanks for review~

**Comment by sdudoladov** [comment]
:+1:

**Comment by sdudoladov** [comment]
@zvier thanks for the contribution !

**Comment by FxKu** [comment]
:+1:

**Comment by zvier** [comment]
> I think you did something wrong in your last push. Your changes are gone. Note, that when we approve a PR you should not push other commits because then we have to approve again. In the end all commits will be squashed anyway on commit.

Hello,  I really do this for try to found the problem whether it is introduced by this PR because the e2e tests ci failed. But even I do nothing even with an empty commit(only delete a blank line) it also failed. So, is the e2e tests any problem ?

**Comment by FxKu** [comment]
Will close this now. Yes the nodeAffinity e2e test fails on GH regularly. Something we should fix at some point.

**Pull request closed without merging**
