### PR TITLE
Fix documentation (actualized links to external resources)

### PR DESCRIPTION
**Pull request by FactorT**
1) Changed link to kubernetes.io/docs due to movement article about pod's termination.
2) Changed link to kube-downscaler due to migration's project to codeberg.
3) Added parameter "pod_environment_secret" and small annotation.

### CODE REVIEW

**Comment by FxKu** [comment]
:+1:

**Comment by idanovinda** [comment]
👍

**Comment by jopadi** [comment]
👍

**Comment by FxKu** [comment]
Thanks @FactorT for the fixes :smiley:

**Pull request merged**
