### PR TITLE
replace AdditionalProperties with XPreserveUnknownFields FIXES  #1206

### LINKED ISSUE #1206: Postgres-operator doesn't let to create sidecars anymore
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** v1.5.0-69-gb379db2-dirty
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

After upgrading to the latest image, I noticed that sidecars definition looks like this:
```
  sidecars:
  - env:
    - {}
    - {}
    - {}
    image: wrouesnel/postgres_exporter
    name: postgres-prometheus-exporter
    ports:
    - {}
    resources: {}
```
Even when I edit and insert proper values they get lost, I compared the crd definition with an older version and I see that `preserveUnknownFields: true` disappeared.

### PR DESCRIPTION
**Pull request by yanchenko-igor**
This patch fixes the bug I reported before #1206

### CODE REVIEW

**Comment by yanchenko-igor** [comment]
Can you help me with the test, I don't understand why it failed.

**Comment by FxKu** [comment]
Ah, I've only changed the validation for OperatorConfiguration CRD, but not Postgres CRD. Thanks. Not sure, what coveralls is complaining. We merge it anyway.

**Comment by FxKu** [comment]
:+1:

**Comment by RafiaSabih** [comment]
:+1:

**Pull request merged**
