### PR TITLE
Config option to allow Spilo container to run non-privileged.

### LINKED ISSUE #395: Option to run containers in non-privileged mode
As far as I can see from 19dfa0c2b025a6aa9d260df13b16b7754110d01c, privileged access is used for AWS volume resizing.

However, I don't want to give my database containers privileged access so it would be great if this could be configurable.

(cc @abh)

### PR DESCRIPTION
**Pull request by aaroniscode**
Runs non-privileged by default.

Fixes #395 

Happy to make any changes if the team prefers a different approach.

### CODE REVIEW

**Comment by FxKu** [comment]
Thanks for your contribution. Could you also introduce the flag in the [ConfigMap](https://github.com/zalando/postgres-operator/blob/master/manifests/configmap.yaml)? This would make it very easy to toggle the privilege mode.

**Comment by sdudoladov** [comment]
@aaroniscode we support two alternative ways to configure the operator : the operator's own CRD and a configmap , configuration option needs to be present in both

**Comment by aaroniscode** [comment]
@sdudoladov I believe the PR supports both methods to configure the operator as I tested with both the ConfigMap AND the CRD.  Am I missing something?

**Comment by sdudoladov** [comment]
@aaroniscode no,  sorry , my mistake.

please add an example config  to the [configmap](https://github.com/zalando/postgres-operator/blob/master/manifests/configmap.yaml), and we will merge the PR

**Comment by aaroniscode** [comment]
@FxKu @sdudoladov added the ConfigMap as requested. Let me know if there is anything else. Thanks for reviewing.

**Comment by FxKu** [comment]
Yes one more thing, sorry :)
Now that we got a Helm chart, the new flag should also be present in its [values.yaml](https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml).

Aside from that, it's fine for me and I can merge today.

**Comment by aaroniscode** [comment]
@FxKu no problem! I added the flag to the chart's values.yaml. I had to rebase and force push as my fork didn't have the helm chart.

**Pull request merged**
