### PR TITLE
fix: make map in generateUserSecrets with correct size

### PR DESCRIPTION
**Pull request by genofire**
just a small finding during reading

### CODE REVIEW

**Comment by FxKu** [comment]
Interesting. Never stumbled over an error related to secret generation. But the code change make sense.

**Comment by dmvolod** [comment]
Seems to most of the cases like this will be covered by linter with additional configuration, still waiting to be merged in #2135

**Comment by FxKu** [comment]
:+1:

**Comment by idanovinda** [comment]
👍

**Pull request merged**
