### PR TITLE
Yet another operator configuration means

### PR DESCRIPTION
**Pull request by rsteppac**
## Problem description

Allow operator configuration via files named like configuration properties with their contents as values to be picked up from a list of configured directories.
The motivation was to allow integration with Hashicorp's Vault injector (rendering secrets to /vault/secrets).
To this end I have also introduced configuration properties for a default S3 secret for WAL backups analogue to the already existing secret for logical backups.

## Linked issues

none

## Checklist

Thanks for submitting a pull request to the Postgres Operator project.
Please, ensure your contribution matches the following items:

- [x] Your go code is [formatted](https://blog.golang.org/gofmt). Your IDE should do it automatically for you.
- [?] You have updated [generated code](https://github.com/zalando/postgres-operator/blob/master/docs/developer.md#code-generation) when introducing new fields to the `acid.zalan.do` api package.
- [x] New [configuration options](https://github.com/zalando/postgres-operator/blob/master/docs/developer.md#introduce-additional-configuration-parameters) are reflected in CRD validation, helm charts and sample manifests.
- [x] New functionality is covered by [unit](https://github.com/zalando/postgres-operator/blob/master/docs/developer.md#unit-tests) and/or [e2e](https://github.com/zalando/postgres-operator/blob/master/docs/developer.md#end-to-end-tests) tests.
- [x] You have checked existing open PRs for possible overlay and referenced them.

### CODE REVIEW

**Comment by rsteppac** [comment]
The e2e test suite failed for the PR. But I cannot reproduce the failure locally. Out of 3 runs the suite finished successfully twice and failed once. The failure was at `test_node_affinity`, not `test_additional_pod_capabilities`.

**Comment by zvier** [comment]
> The e2e test suite failed for the PR. But I cannot reproduce the failure locally. Out of 3 runs the suite finished successfully twice and failed once. The failure was at `test_node_affinity`, not `test_additional_pod_capabilities`.

I have the same problem with my pr ? Any one can fix this problem  :cry:

**Comment by rsteppac** [comment]
@avaczi , @CyberDem0n , @erthalion , @FxKu , @Jan-M , @RafiaSabih , @sdudoladov , my apologies if I come across as pushy.  
My PR has been around for a while now. Is there anything else I should provide so the PR can be considered for review?

Thanks and regards,
Ralf

**Comment by FxKu** [comment]
Wow, over one year already. Sorry @rsteppac . I don't see when you cannot use [pod_enviornment_configmap/secret](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#custom-pod-environment-variables) instead for stuff like s3 id and s3 key?

Overwriting directories sounds like you should rather look at patching spilo to support you setup.

**Pull request closed without merging**
