### PR TITLE
Match formatting in both chart values files

### PR DESCRIPTION
**Pull request by apeschel**
There are currently two values files:

* values.yaml
* values-crd.yaml

There are a large number of insignificant formatting changes between the
two, which obscures the actual changes between the two files.

This commit standardizes the formatting between the two files.

### CODE REVIEW

**Comment by apeschel** [comment]
Hello, while looking at values.yaml and values-crd.yaml to see what the difference was between the two files, I noticed that there are a lot of formatting difference, which have no impact but obscure the actual differences between the two files. This PR just cleans up the formatting to make it consistent between the two files. There is no logical difference between the two files.

**Comment by apeschel** [comment]
Looks like there's a problem with CI at the moment. This changeset has no impact on the CI pipeline at all.

**Comment by apeschel** [comment]
CI is fixed in https://github.com/zalando/postgres-operator/pull/1345

**Comment by apeschel** [comment]
It looks like more work is required here, since the validator validates each file with different types for some reason.

**Comment by FxKu** [comment]
Will close this PR since we merged the two `values` files. Could be that there is is still some inconsistency with our manifest examples, but that's stuff for another PR.

**Pull request closed without merging**
