### PR TITLE
Update UI library dependencies

### PR DESCRIPTION
**Pull request by idanovinda**
Updating Python and Javascript libraries for the UI.

### CODE REVIEW

**Comment by FxKu** [comment]
cannot build this locally:

```
docker run -it -u $(id -u) -v $(pwd):/workdir -w /workdir/app node:16.19.0-alpine npm run build

> postgres-operator-ui@1.8.2 build
> NODE_ENV=development npm run webpack

npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
npm WARN logfile   errno: -13,
npm WARN logfile   code: 'EACCES',
npm WARN logfile   syscall: 'scandir',
npm WARN logfile   path: '/root/.npm/_logs'
npm WARN logfile }

> postgres-operator-ui@1.8.2 prewebpack
> npm run clean

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_cacache/tmp
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1217546946:1217400513 "/root/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /root/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
npm notice 
npm notice New major version of npm available! 8.19.3 -> 9.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.4.0
npm notice Run npm install -g npm@9.4.0 to update!
npm notice 
make: *** [Makefile:25: appjs] Error 243
```

**Comment by FxKu** [comment]
Uncaught Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Module.<anonymous> (js-yaml.mjs:3794:1)
    at Object.requestCreate (new.tag.pug:806:9)
    at Object.handleEvent (riot.js:1456:1)

**Comment by FxKu** [comment]
:+1:

**Comment by idanovinda** [comment]
👍

**Pull request merged**
