### PR TITLE
Fix pooler delete

### LINKED ISSUE #961: Deletion of connection pooler incorrectly handles ResourceNotFound
With 1.5 the new connection pooler was added. In the function to delete the corresponding resources there is a check if the error returned from the K8S API is `ResourceNotFound` (good, as we wanted to delete it anyways), see https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/resources.go#L194

But it seems to me the condition wrongly checks for the opposite case - so if it NOT this error.
I prepared a PR to adjust this: https://github.com/zalando/postgres-operator/pull/960

### PR DESCRIPTION
**Pull request by frittentheke**
fixes #961

### CODE REVIEW

**Comment by FxKu** [comment]
Can you provide at least one sentence in the PR body. zappr doesn't like empty descriptions :)
LGTM, though.

**Comment by FxKu** [comment]
:+1:

**Comment by erthalion** [comment]
Thanks for noticing @frittentheke !

**Comment by erthalion** [comment]
:+1:

**Pull request merged**
