### PR TITLE
bump to v1.10.0

### PR DESCRIPTION
**Pull request by FxKu**
- [x] bump operator image
- [x] bump Spilo image
- [x] bump logical backup image
- [x] update go dependencies (incl. #2293)
- [x] add missing config option to docs
- [x] update year in LICENSE file

### CODE REVIEW

**Comment by thcdrt** [comment]
Hello, 

Do we know when this will be released ? :)
Is it possible to add this fix https://github.com/zalando/postgres-operator/pull/2297 or is is too late ?

Thanks !

Thomas

**Comment by FxKu** [comment]
@thcdrt thanks for catching this. There's still time. Wanted to release today. Lets merge your PR and let me update the operator chart here.

**Comment by basaveswar-kureti** [comment]
Getting the following error in 1.10 for postgres-ui-operator. UI is also not loading.
1.9 is good.

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 978, in emit
    self.socket.send(msg)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
  File "/usr/lib/python3.9/site-packages/gevent/_socket3.py", line 55, in _dummy
    raise OSError(EBADF, 'Bad file descriptor')
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 899, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 628, in connect
    raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 981, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.9/logging/handlers.py", line 910, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 628, in connect
    raise _SocketError(result, strerror(result))
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/operator_ui/__main__.py", line 3, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/operator_ui/main.py", line 1145, in main
    logger.info(f'Listening on :{port}')
Message: 'Listening on :8081'
```

**Comment by basaveswar-kureti** [comment]
Filed a bug here : https://github.com/zalando/postgres-operator/issues/2302

**Pull request closed without merging**
