### PR TITLE
document configmap variant of inherited_labels

### PR DESCRIPTION
**Pull request by knan-nrk**
As discussed with @FxKu on slack Oct 4 :)

### CODE REVIEW

**Comment by FxKu** [comment]
Thanks @knan-nrk . Could you also update the two Helm chart values files accordingly, please?

**Comment by knan-nrk** [comment]
Sure. Missed them since they're not under manifests/.

**Comment by FxKu** [comment]
:+1:

**Comment by RafiaSabih** [comment]
:+1:

**Pull request merged**
