### PR TITLE
Kustomization

### PR DESCRIPTION
**Pull request by jakub-roman**
Add ability to install the operator via kustomization as proposed in #607

### CODE REVIEW

**Comment by FxKu** [comment]
Thanks for the contributions. Another K8s tool, I've never heard about ^^
I'm not sure on providing an example and put yet another section in the quickstart. Maybe it's enough to just mentioning it in one sentence for the manual setup.

**Comment by Jan-M** [comment]
I like it. Seems pretty slim. Maybe it can be reduced to the instructions how to install with kubectl, incl. brief min version?

Maybe we can also slim down the Helm section to the most basic instructions and not too many words about helm.

**Comment by yujunz** [comment]
> Thanks for the contributions. Another K8s tool, I've never heard about ^^
> I'm not sure on providing an example and put yet another section in the quickstart. Maybe it's enough to just mentioning it in one sentence for the manual setup.

It is a built-in plugin in recent Kubectl release. For quickstart, one line instruction on the version constraint and some link might be good enough.

**Comment by yujunz** [comment]
By the way, the manifests is kind of out of date comparing to helm chart output

**Comment by FxKu** [comment]
I've added a sentence about Kustomization in PR #609. So we could close this PR then.

@yujunz it can be that the original Helm chart author followed some best practices from the Helm docs. If you see any bigger differences, please open another issue to discuss it.

**Comment by FxKu** [comment]
It's now mentioned in the [Quickstart](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#manual-deployment-setup). Thanks again @jakub-roman for pointing us to this feature :)

**Comment by jakub-roman** [comment]
@FxKu the main value of this PR was the `manifests/kustomization.yaml` file - without it the kustomization won't work magically. I don't really care much about docs, just wanted to make it more verbose because kustomize is somehow young tool and people don't know much about it yet.

The idea was that you manage the kustomization file in this repository - you are the ones who know how to install the operator properly after all - so people doesn't have to know which manifests to use. 

The alternative is that people make their own kustomization files (which is already redundant), but then if you decide to add another manifest file necessary to install the operator everyone that uses kustomization will have to know about that change and make amendments in their kustomization files and that's just painful...

P.S. sorry I'm coming back to this so late, I didn't have access to internet last week

**Comment by Jan-M** [comment]
We will add the file ;)

**Comment by jakub-roman** [comment]
> We will add the file ;)

Should I just remove the quickstart docs since you already have a note about it so you can merge in this one?

**Comment by FxKu** [comment]
Yes. Or you can add one more sentence with a link to the provided Kustomization file. Then i'll merge it.

**Comment by FxKu** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:

**Comment by FxKu** [comment]
@jakub-roman thanks for your contribution :)

**Comment by jakub-roman** [comment]
Thanks for including this, it makes the installation way easier for us :)

**Pull request merged**
