### PR TITLE
standby-cluster-gs

### PR DESCRIPTION
**Pull request by anshudutta**
Currently, there is a bug which doesn't allow standby cluster to be created from WAL archives from GCP Bucket

Error:

```
Error: postgresql.acid.zalan.do "alchemy-database" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"acid.zalan.do/v1", "kind":"postgresql", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"meta.helm.sh/release-name":"alchemy", "meta.helm.sh/release-namespace":"alchemy"}, "creationTimestamp":"2020-07-13T06:19:13Z", "generation":1, "labels":map[string]interface {}{"app.kubernetes.io/managed-by":"Helm"}, "name":"alchemy-database", "namespace":"postgres-operator", "uid":"80eca2c8-8959-4c8e-a84e-bc8ff64a965a"}, "spec":map[string]interface {}{"numberOfInstances":1, "patroni":map[string]interface {}{"pg_hba":[]interface {}{"host    all all 0.0.0.0/0 md5"}}, "postgresql":map[string]interface {}{"version":"11"}, "standby":map[string]interface {}{"gs_wal_path":"gs://pgbucket-rl-af7b0aec/spilo/alchemy-database"}, "teamId":"alchemy", "volume":map[string]interface {}{"size":"10Gi", "storageClass":"ssd-alchemy"}}}: validation failure list:
 spec.standby.s3_wal_path in body is required
```
This is because the `s3_wal_path` property is mandatory even when using GCP.

This PR is aimed at fixing that bug

Changes:
1. Spin up a standby cluster using WAL archives from GCP bucket
2. Either s3_wal_path or gs_wal_path are mandatory
3. Setting gs_wal_path will set set environment variable STANDBY_WALE_GS_PREFIX which will then be used by wal-g to use gcp sdk

### CODE REVIEW

**Comment by fcrespofastly** [comment]
@anshudutta Thanks for this PR!! I'm going to be testing these changes, would you mind resolving rebasing from master? Thanks!!

**Comment by anshudutta** [comment]
Thanks. I have rebased from master

**Comment by fcrespofastly** [comment]
@anshudutta @FxKu I'll be testing this today

**Comment by fcrespofastly** [comment]
From what I can tell, it is not working for me. 

I'm adding: 

`gs_wal_path:  gs://<BUCKET_NAME>/spilo/<CLUSTER_NAME>`

but I keep getting:

```
 trying to bootstrap a new standby leader
Can not find any backups
2020-09-29 13:43:36,581 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1
2020-09-29 13:43:36,582 ERROR: failed to bootstrap clone from remote master None
```

So I think remote  master `None` it's obviously wrong, but I fail to see why. So maybe I'm not setting that correctly? 

cc/ @anshudutta @FxKu

**Comment by fcrespofastly** [comment]
How can I make it use WALG instead?

**Comment by FxKu** [comment]
> Thanks. I have rebased from master

@anshudutta I think you have merge with master but not properly rebased as I see many commits from previous PRs :smiley: 
This makes it hard now to inspect only your changes.

**Comment by fcrespofastly** [comment]
> > Thanks. I have rebased from master
> 
> @anshudutta I think you have merge with master but not properly rebased as I see many commits from previous PRs 😃
> This makes it hard now to inspect only your changes.

yeah I saw the same 😅

**Comment by anshudutta** [comment]
I have rebased it but I am not sure why it keeps showing files in diff which are not mine

**Comment by anshudutta** [comment]
> From what I can tell, it is not working for me.
> 
> I'm adding:
> 
> `gs_wal_path: gs://<BUCKET_NAME>/spilo/<CLUSTER_NAME>`
> 
> but I keep getting:
> 
> ```
>  trying to bootstrap a new standby leader
> Can not find any backups
> 2020-09-29 13:43:36,581 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1
> 2020-09-29 13:43:36,582 ERROR: failed to bootstrap clone from remote master None
> ```
> 
> So I think remote master `None` it's obviously wrong, but I fail to see why. So maybe I'm not setting that correctly?
> 
> cc/ @anshudutta @FxKu

That error happens when the backups are corrupted in the gs bucket or are trying to pull from a different master.
This is working in our production cluster.

**Comment by anshudutta** [comment]
> From what I can tell, it is not working for me.
> 
> I'm adding:
> 
> `gs_wal_path: gs://<BUCKET_NAME>/spilo/<CLUSTER_NAME>`
> 
> but I keep getting:
> 
> ```
>  trying to bootstrap a new standby leader
> Can not find any backups
> 2020-09-29 13:43:36,581 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1
> 2020-09-29 13:43:36,582 ERROR: failed to bootstrap clone from remote master None
> ```
> 
> So I think remote master `None` it's obviously wrong, but I fail to see why. So maybe I'm not setting that correctly?
> 
> cc/ @anshudutta @FxKu

That error happens when the backups are corrupted in the gs bucket or are trying to pull from a different master.
This is working in our production cluster. 
cc @dyla

> > Thanks. I have rebased from master
> 
> @anshudutta I think you have merge with master but not properly rebased as I see many commits from previous PRs 😃
> This makes it hard now to inspect only your changes.

Yeah. not sure why.
But the gist of changes - 
https://github.com/zalando/postgres-operator/pull/1058/commits/172e19f7bd902a37cc76b172672db93099738ceb

Its really simple

**Comment by fcrespofastly** [comment]
I can clone from backup, so it's not corrupted.

I think the key is master `None` in the error. I'm wondering if there's anything I am not setting properly

**Comment by jean-mercier-hivebrite** [comment]
This feature is abandoned ? or could we hope to see it ?

**Comment by FxKu** [comment]
Closing in favor for #1446

**Pull request closed without merging**
