### PR TITLE
Use scram-sha-256 hash if postgresql parameter password_encryption set to do so.

### PR DESCRIPTION
**Pull request by yanchenko-igor**
Implemented scram-sha-256 to encrypt the password.

### CODE REVIEW

**Comment by yanchenko-igor** [comment]
Is anything wrong about this PR? our goal is to disable md5 in favor of scram-sha256, we could provide already encrypted passwor, but we would need postgres-operator to ignore password strings which start with "SCRAM-SHA-256$", could we do at least that?

**Comment by FxKu** [comment]
@yanchenko-igor can you rebase? I see some unrelevant changes here. In general, we nothing against this PR and would merge it soon. :smiley:

**Comment by yanchenko-igor** [comment]
> @yanchenko-igor can you rebase? I see some unrelevant changes here. In general, we nothing against this PR and would merge it soon. smiley

@FxKu i rebased, the only irrelevant change is to travis config, without this change goveralls ignores some tests and doesn't show coverage of the new code, let me know if you would prefer to fix it in a separate PR.

**Comment by FxKu** [comment]
@yanchenko-igor yes can you move this part to a separate PR? Aside from that the PR looks fine.

**Comment by yanchenko-igor** [comment]
All right, I removed the commit with travis settings, as expected, the coverage test didn't pass. Here is the change which will increase the coverage https://github.com/zalando/postgres-operator/pull/1055 .

**Comment by yanchenko-igor** [comment]
now it passes the coverage test 🎉

**Comment by FxKu** [comment]
:+1:

**Comment by CyberDem0n** [comment]
:+1:

**Pull request merged**
