### PR TITLE
Fix typo in values file

### PR DESCRIPTION
**Pull request by Jonher937**
Fix typo: spelling

### CODE REVIEW

**Comment by FxKu** [comment]
@Jonher937 thanks for finding it. Can you replace the type everywhere? I've found it also in two other places.

**Comment by Jonher937** [comment]
I just saw the one looking thru the values file.
The other occurrences should be fixed now, as well as a indent in one of the markdown files.

**Comment by erthalion** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Pull request merged**
