### PR TITLE
Introduce ENABLE_JSON_LOGGING env variable

### LINKED ISSUE #1157: Feature Request: JSON Logging for Operator
- **Which image of the operator are you using?**
registry.opensource.zalan.do/acid/postgres-operator:v1.5.0

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
AKS engine

- **Are you running Postgres Operator in production?**
not yet

- **Type of issue?**
Feature Request

Some logging stacks rely on / prefer application logs in JSON format. Currently there is no option to enable JSON logging for the postgres operator. That would be a very useful feature to have.

### PR DESCRIPTION
**Pull request by dajudge**
Fix #1157

### CODE REVIEW

**Comment by dajudge** [comment]
I'm not sure if it's worth implementing a test here given the minimal change in coverage and the non-functional nature of the PR. What's your opinion on this?

**Comment by Jan-M** [comment]
Looks good to me, also with the "limited" amount of tests. And seems this new introduced dependency to do logging is also widely used.

**Comment by Jan-M** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks @dajudge for your contribution!

**Comment by dajudge** [comment]
@Jan-M @FxKu Thanks for the quick feedback and integration into master!

Do you have any information on when a release w/ the changes is planned?

**Pull request merged**
