### PR TITLE
Don't emit FAILED k8s event on successful switchover

### PR DESCRIPTION
**Pull request by mwpeterson**
Fixes issue #1134

### CODE REVIEW

**Comment by Jan-M** [comment]
Thanks for the PR.

Would you mind to actually move this emit into the two different error cases above, and emit different messages.

Reason:
1) Switch failed because patroni call failed , which may also still be successfull
2) Switch call was succesfull, but promote is slow (which means user just needs to wait)

**Comment by Jan-M** [comment]
And 3. emit success if this is not happening already somewhere else.

**Comment by Jan-M** [comment]
@mwpeterson any chance you will make the changes?

**Comment by mwpeterson** [comment]
Yes. This weekend.

**Comment by mwpeterson** [comment]
Closing until I _actually_ can find time to rework this. My apologies.

**Pull request closed without merging**
