### PR TITLE
update K8s version and reflect necessary changes

### PR DESCRIPTION
**Pull request by FxKu**
I intentionally did not change it for v1.13.0 because I'm not sure if the operator would then stop working for K8s 1.28- any longer.

### CODE REVIEW

**Review by macedigital — APPROVED** [review]
Looks good to me. I wouldn't expect the changes to be backward necessarily incompatible with 1.28.x, but highly recommend to mention this as potentially breaking change.

Wouldn't it also be possible to spin up a 1.28.x minikube cluster to check for compatibility ?

**Comment by macedigital** [comment]
:+1:

**Comment by FxKu** [comment]
I tested with minikube 1.28 and I could spin up clusters. Therefore, we can merge it.

**Comment by FxKu** [comment]
:+1:

**Pull request merged**
