### PR TITLE
Logical backup retention time

### PR DESCRIPTION
**Pull request by stoewer**
This PR adds the possibility to configure a retention time for logical backups (as described in #1008).

The cleanup of logical backup objects, older than the defined retention period, is implemented in the `dump.sh` script and will only run after a successful upload of a new backup.

The retention time can be configured using the parameter `logical_backup_s3_retention_time`. Values can be specified in a human friendly format such as `1 week` or `2 months`. Values shorter than one day (e.g. `3 hours`) are accepted but will be rounded up to a full day. As a precaution the cleanup procedure will always spare the newest backup that is older than the retention time.

### CODE REVIEW

**Comment by stoewer** [comment]
👍

**Comment by stoewer** [comment]
👍

**Comment by sdudoladov** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks @stoewer for your contribution and sorry it took us so long to merge.

**Comment by stoewer** [comment]
@FxKu thank you for reviewing and merging
> ... sorry it took us so long to merge.

No worries, a true #1337 PR deserves to stay open for a while :)

**Comment by Routhinator** [comment]
How do we configure this from the CRD config?

**Comment by FxKu** [comment]
@Routhinator what do you mean? You can set `logical_backup_s3_retention_time` in either ConfigMap or OperatorConfiguration CRD. Not from the Postgresql manifest, though.

**Comment by Routhinator** [comment]
I mean I would like to set this for the cluster CRD so that different clusters have different retention. I found the global config - but I need per-cluster config.

**Comment by thcdrt** [comment]
Hello, what happened when the postgres CR is deleted. Backup are not cleaned up anymore, right ?

**Pull request merged**
