### PR TITLE
feat: Add extraEnvs to operator-ui helm chart

### LINKED ISSUE #1523: Postgre Operator UI chart improvement
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator-ui:v1.6.2
- **Where do you run it - cloud or metal?** EKS
- **Are you running Postgres Operator in production?** no
- **Type of issue?** feature request

It would be great to add more option to postgres operator ui chart like:
- Add more ENV Variable ( SPILO_S3_BACKUP_BUCKET, USE_AWS_INSTANCE_PROFILE, WALE_S3_ENDPOINT, ...)
- Update operator ui config (postgresql_versions, replica_load_balancer_visible, master_load_balancer_visible, ....) 

I could make a pull request for this features but before starting developping them,  I want to be sure that anyone doesn't already work on them.

Thanks

### PR DESCRIPTION
**Pull request by golgoth31**
This PR allows adding any needed extra anv vars to the operator-ui deployment into the helm chart.
Fixes #1523

### CODE REVIEW

**Comment by FxKu** [comment]
Thanks. Lets add these commented lines directly to the deployment template and [example manifest](https://github.com/zalando/postgres-operator/blob/master/ui/manifests/deployment.yaml).

**Comment by golgoth31** [comment]
Is it what you intended ?

**Comment by FxKu** [comment]
Yes and the same for helm chart, too. This `extraEnvs` construct looks kinda strange to me.

**Comment by golgoth31** [comment]
I have added some comments in the values.yaml file the extraEnvs field
```
# configure extra UI ENVs
# Extra ENVs are writen in kubenertes format and added "as is" to the pod's env variables
# https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables
# UI specific env variables can be found here: https://github.com/zalando/postgres-operator/blob/master/ui/operator_ui/main.py
```
does it seems ok ?

**Comment by Jan-M** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks @golgoth31 for your contribution! :smiley:

**Comment by golgoth31** [comment]
Thank you for this amazing job !

**Pull request merged**
