### PR TITLE
Simplify service account name in helm chart

### LINKED ISSUE #610: Ugly format of helm template output
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name:
            RELEASE-NAME-postgres-operator
```

Rendered out of

```
  name: {{- if eq .Values.serviceAccount.name "" }}
            {{ template "postgres-operator.fullname" . }}
        {{- else }}
            {{ .Values.serviceAccount.name }}
        {{- end }}
```

It does not affect usage, but looks ugly when previewed with `helm template` or dumped to [raw manifests for kustomize](https://github.com/kustless/postgres-operator/blob/master/base/clusterrole.yaml)

### PR DESCRIPTION
**Pull request by yujunz**
Fix #610

### CODE REVIEW

**Comment by FxKu** [comment]
Great! Just tested it and everything works as expected. One small remark: In the two values files could you change the serviceAccount name settings.

- values: name: "" -> name:
- values-crd: name: "operator" -> operator

This is what I've tested and it follows helm chart best practices.

**Comment by yujunz** [comment]
> * values: name: "" -> name:
> * values-crd: name: "operator" -> operator

Done

**Comment by FxKu** [comment]
awesome. Thanks

**Comment by FxKu** [comment]
:+1:

**Comment by sdudoladov** [comment]
:+1:

**Pull request merged**
