### PR TITLE
Add a switch to turn off pvc retention policy (#2599)

### LINKED ISSUE #2599: PersistentVolumeClaim retention is feature-gated and should be handled conditionally
After upgrading to v1.11.0 I noticed the following messages for every postgres cluster on every start up of the operator:

```
time="2024-04-04T16:56:37Z" level=info msg="statefulset myapp/myapp-postgres is not in the desired state and needs to be updated" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-          terminationMessagePath: /dev/termination-log," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-          terminationMessagePolicy: File," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      restartPolicy: Always," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      dnsPolicy: ClusterFirst," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      serviceAccount: postgres-pod," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      securityContext: {}," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      schedulerName: default-scheduler" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="+      securityContext: {}" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      kind: PersistentVolumeClaim," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      apiVersion: v1," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      status: {" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-        phase: Pending" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-      }" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="+      status: {}" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="-  revisionHistoryLimit: 10" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="+  persistentVolumeClaimRetentionPolicy: {" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="+    whenDeleted: Retain," cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="+    whenScaled: Retain" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="+  }" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=info msg="reason: new statefulset's persistent volume claim retention policy do not match" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="replacing statefulset" cluster-name=myapp/myapp-postgres pkg=cluster
time="2024-04-04T16:56:37Z" level=debug msg="waiting for the statefulset to be deleted" cluster-name=myapp/myapp-postgres pkg=cluster
```

After that nothing happens. The sts is neither deleted nor fixed and the messages show up on every start of the operator.

The cluster is running version k8s 1.25. It is my understanding that PersistentVolumeClaims are behind a feature-gate even in version 1.27 and that those parts of the sts spec can never be set. Indeed, trying to set them manually fails. See: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

The operator should not attempt to set those values if the feature is not available.

### PR DESCRIPTION
**Pull request by bo0ts**
Fixes #2599

### CODE REVIEW

**Comment by FxKu** [comment]
Hm, isn't the retention policy something we always want to set in the long run. I've [checked](https://stackoverflow.com/questions/69446495/how-should-i-retrieve-the-current-kubernetes-server-version-via-golang-codes) if it's also possible to retrieve the K8s/OpenShift ServerVersion to decide when to add it. Seems easier now than adding another config option which needs changes in many places (you haven't covered them all).

**Comment by bo0ts** [comment]
@FxKu I'm not sure about that. Is the k8s version enough? Don't we also need to check for the feature flag?

**Comment by FxKu** [comment]
That I don't know. But maybe also accessible like the ServerVersion. Can you check?

**Comment by angelsantillana94** [comment]
any update?

**Comment by FxKu** [comment]
Yeah, I have updated min required K8s version to 1.27 in the README :smiley: 
No, seriously, I would still suggest to add a simple if that checks the server version. I was hoping somebody from the community can show me how to do this. Over the last months we went through multiple K8s major version updates, so I would assume others can do it, too. 1.26- is already quite old.

**Comment by bo0ts** [comment]
Hey, we do not need this feature anymore.

**Pull request closed without merging**
