### PR TITLE
Logical backup secret

### PR DESCRIPTION
**Pull request by stgrace**
See #2050

### CODE REVIEW

**Comment by robertlandrum** [comment]
The other implementation is "probably" better.  Mine is definitely simpler.  I'm not sure which warrants inclusion in the next release, but can say I've deployed mine to our non-prod environments.

**Comment by KlavsKlavsen** [comment]
Whats holding this back? or have 2 who can approve just not reviewed it yet?

**Review by yajo — APPROVED** [review]

**Review by nihaldivyam — APPROVED** [review]

**Comment by ashish1099** [comment]
Any update, we are waiting on this one for long

**Comment by KlavsKlavsen** [comment]
@yajo @nihaldivyam I see you both approved this.. and yet the ZAPPR status says its "pending 2 approvals - 0/2 given" ?

**Comment by ashish1099** [comment]
@yajo @nihaldivyam thank you for approving, any update on when this can be merged. ?

**Comment by yajo** [comment]
I have no authority in this project, no idea. I see this one has conflicts though, so even maintainers won't be able to merge.

**Comment by stgrace** [comment]
@yajo should be solved now

**Comment by FxKu** [comment]
@stgrace thanks for providing this feature. I will have a look. You have to fix your unit test, too? Only +1 from project maintainers count for zappr btw.

**Comment by jonathon2nd** [comment]
Looking forward to this being done :smile: 
Right now managing the cronjobs manually, but every so often the operator wants to update them and places invalid config, because I do not set `configLogicalBackup`

**Comment by nihaldivyam** [comment]
@stgrace  Eagerly waiting for this to get merged !!

**Comment by KlavsKlavsen** [comment]
@FxKu thank you for adding this to a milestone - but when will it be merged? its a "small thing" - and its really annoying we have to implement our until this works properly :(

**Comment by jiuker** [comment]
@KlavsKlavsen we need this too.

**Comment by drivebyer** [comment]
@FxKu  Eagerly waiting for this to get merged too !

**Comment by stgrace** [comment]
Hi everyone, 
First of all sorry for the late response, I've been busy.
I've fixed the unit tests, but the e2e tests are failing for the label testing, which is not related to my PR, so not sure why that is failing and if I can fix it.
```
======================================================================
FAIL: test_node_affinity (test_e2e.EndToEndTestCase)
Add label to a node and update postgres cluster spec to deploy only on a node with that label
```
@FxKu

**Comment by ashish1099** [comment]
@FxKu can you please look in the above issues

**Comment by szechp** [comment]
it would be nice if this got merged, no one wants their s3 credentials in plain text :)

**Comment by FxKu** [comment]
:+1:

**Comment by idanovinda** [comment]
👍

**Comment by FxKu** [comment]
Thanks @stgrace for your contribution and sorry it took us so long too merge it.

**Pull request merged**
