### PR TITLE
Improving e2e more

### PR DESCRIPTION
**Pull request by Jan-M**
* More waits for cluster to be ok at end of test
 * Added curl to operator image to allow getting API without port forward and stuff.

### CODE REVIEW

**Comment by sdudoladov** [comment]
I see locally failures similar to those CDP reports
```
Get databases: su postgres -c "psql -tAq -c \"select datname from pg_database\" 
-d postgres"                                        
dbList: ['postgres', 'bar', 'template1', 'template0', 'foo'], stdout: b'postgres
\nbar\ntemplate1\ntemplate0\nfoo\n', stderr b''          
Get schemas: su postgres -c "psql -tAq -c \"                                    
            select schema_name                           
            from information_schema.schemata                                    
            where schema_name = 'pooler'                 
        \" -d postgres"                                                         
schemas: ['pooler'], stdout: b'pooler\n', stderr b''     
Get schemas: su postgres -c "psql -tAq -c \"                                    
            select schema_name
            from information_schema.schemata
            where schema_name = 'pooler'
        \" -d bar"
schemas: ['pooler'], stdout: b'pooler\n', stderr b''
Get schemas: su postgres -c "psql -tAq -c \"
            select schema_name
            from information_schema.schemata
            where schema_name = 'pooler'
        \" -d foo"
Expected key annotation.key not found in annotations None
...
Expected key deployment-time not found in annotations {'zalando-postgres-operato
r-rolling-update-required': 'false'}
Expected key deployment-time not found in annotations {'zalando-postgres-operato
r-rolling-update-required': 'false'}
Expected key deployment-time not found in annotations {'zalando-postgres-operato
r-rolling-update-required': 'false'}

```

**Comment by sdudoladov** [comment]
can you also put `SPILO_CONFIGURATION` into a nicely diffed format  so that these log lines become more readable
```
time="2020-10-29T07:00:59Z" level=debug msg="Generating Spilo container, environment variables" cluster-name=default/acid-minimal-cluster pkg=cluster
time="2020-10-29T07:00:59Z" level=debug msg="[{SCOPE acid-minimal-cluster nil} {PGROOT /home/postgres/pgdata/pgroot nil} {POD_IP  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.podIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {POD_NAMESPACE  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {PGUSER_SUPERUSER postgres nil} {KUBERNETES_SCOPE_LABEL cluster-name nil} {KUBERNETES_ROLE_LABEL spilo-role nil} {PGPASSWORD_SUPERUSER  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres.acid-minimal-cluster.credentials,},Key:password,Optional:nil,},}} {PGUSER_STANDBY standby nil} {PGPASSWORD_STANDBY  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:standby.acid-minimal-cluster.credentials,},Key:password,Optional:nil,},}} {PAM_OAUTH2 https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees nil} {HUMAN_ROLE zalandos nil} {KUBERNETES_LABELS {\"application\":\"spilo\"} nil} {SPILO_CONFIGURATION {\"postgresql\":{\"bin_dir\":\"/usr/lib/postgresql/12/bin\"},\"bootstrap\":{\"initdb\":[{\"auth-host\":\"md5\"},{\"auth-local\":\"trust\"}],\"users\":{\"zalandos\":{\"password\":\"\",\"options\":[\"CREATEDB\",\"NOLOGIN\"]}},\"dcs\":{}}} nil} {DCS_ENABLE_KUBERNETES_API true nil}]" cluster-name=default/acid-minimal-cluster pkg=cluster
time="2020-10-29T07:00:59Z" level=debug msg="set statefulset's rolling update annotation to false: caller/reason from cache" cluster-name=default/acid-minimal-cluster pkg=cluster
```

**Comment by Jan-M** [comment]
:+1:

**Comment by Jan-M** [comment]
@sdudoladov as for the spilo env var, we lack a function now with good name and in a good package, so future work.

**Comment by sdudoladov** [comment]
:+1:

**Pull request merged**
