### PR TITLE
add service for exposing operator api

### PR DESCRIPTION
**Pull request by siku4**
I added a k8s service (Helm template) for exposing the operator api. I needed it for running the UI as a separate pod.

### CODE REVIEW

**Comment by Jan-M** [comment]
:+1:

**Comment by FxKu** [comment]
@siku4 could you also create a manifest file in [this](https://github.com/zalando/postgres-operator/tree/master/manifests) directory? The name of the file could be `api-service.yaml` and as for metadata.name maybe `postgres-operator-api`.

**Comment by FxKu** [comment]
:+1:

**Comment by FxKu** [comment]
Merged it for now. I can also make the suggested changes in another PR. Thanks for your contribution @siku4 !

**Pull request merged**
