### PR TITLE
Fix typo in operatorconfigurations CRD

### PR DESCRIPTION
**Pull request by dervoeti**
defaults -> default
Noticed the typo because I got an error while trying to update the CRD in my cluster

### CODE REVIEW

**Comment by FxKu** [comment]
D'oh. Thanks. Can you update it [here](https://github.com/zalando/postgres-operator/blob/f927d6616c186de0aa1789d94a537551049da8d1/manifests/operatorconfiguration.crd.yaml#L456), too?

**Comment by dervoeti** [comment]
Sure, done

**Comment by FxKu** [comment]
:+1:

**Comment by sdudoladov** [comment]
:+1:

**Comment by sdudoladov** [comment]
@dervoeti thanks for catching it :+1:

**Pull request merged**
