### PR TITLE
Fix (#2644) - Add json tags to InfrastructureRole struct

### PR DESCRIPTION
**Pull request by hemakshis**
Fixes: #2644

### CODE REVIEW

**Comment by FxKu** [comment]
Thanks. All the other mappings in this config file use `name:...` instead of `json:...`. Can you test if it also works with name?

**Comment by FxKu** [comment]
I feel we could also more tests and docs on this topic. But for now we can merge as is to include it into today's release.

**Comment by hemakshis** [comment]
It is working after adding `name` tag as well, do you want me to revert it? 😅

**Comment by hemakshis** [comment]
> I feel we could also more tests and docs on this topic. But for now we can merge as is to include it into today's release.

Yes, docs are very confusing and each doc file gives some extra information which is not present in another. It would be good to make it consistent for all the ways we can provide these infra roles - CRD, ConfigMap and then both Only secrets & both Secret+ConfigMap.

**Comment by FxKu** [comment]
:+1:

**Comment by idanovinda** [comment]
👍

**Pull request merged**
