### PR TITLE
update postgres-operator deployment to apps/v1

### LINKED ISSUE #565: Move to apps/v1 API
We face issues similar [to that one ](https://github.com/GoogleCloudPlatform/microservices-demo/commit/d5db0247638840cdb6ed6684c7582f82ac7597b0)
The problem manifests with 
```
unable to apply changes: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"application":"postgres-operator", "name":"postgres-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
some APIs to consider for deprecation: `apps/v1beta1` , `extensions/v1beta1`

Known workaround: completely delete the operator deployment before re-submitting it.

### PR DESCRIPTION
**Pull request by knan-nrk**
update postgres-operator deployment to apps/v1

Fixes #565 .

### CODE REVIEW

**Comment by Jan-M** [comment]
:+1:

**Comment by Jan-M** [comment]
You beat us too it :D thanks.

**Comment by knan-nrk** [comment]
You're welcome! Had the patch lying around from a few weeks ago :)

**Comment by sdudoladov** [comment]
:+1:

**Comment by sdudoladov** [comment]
@knan-nrk  thank you for yet another contribution

**Pull request merged**
