### PR TITLE
Add support for PostgreSQL 16

### PR DESCRIPTION
**Pull request by tm604**
Since pg16 has been released:

https://www.postgresql.org/about/news/postgresql-16-released-2715/

here's an attempt at adding support.

### CODE REVIEW

**Comment by FxKu** [comment]
We do need a Spilo image that supports 16, too :smiley: 
We are on it and when it's ready I let you know so you can update the image, too. Then we can merge this PR

**Comment by Jan-M** [comment]
:+1:

**Comment by tm604** [comment]
Thanks - I created a pull request there, since that makes it a bit easier for local deployment and testing. Note the comment which mentions there's already a `dev-16` branch, it is likely a better starting point for anyone else reading this!

https://github.com/zalando/spilo/pull/944

**Comment by lenglet-k** [comment]
Hello, have you an eta for this pr ?

**Comment by FxKu** [comment]
:+1:

**Comment by FxKu** [comment]
@lenglet-k now :smiley: - this only makes operator accept manifests with 16. More changes are required, see #2557

**Comment by idanovinda** [comment]
👍

**Pull request merged**
