### PR TITLE
Add configuration flag for disabling operator CRD creation/update

### PR DESCRIPTION
**Pull request by dpeckett**
In many applications having the operator dynamically creating/updating CRDs isn't desirable eg. #1393.

This PR introduces a new configuration flag `enable_crd_registration` that can be used to disable the automatic CRD creation/update process. Also included is a modification to the operator chart to allow dropping CRD create/update RBAC permissions when CRD registration is disabled.

### CODE REVIEW

**Comment by imusmanmalik** [comment]
+1

**Comment by microwaves** [comment]
+1 very needed option to avoid conflicts with ArgoCD

**Comment by FxKu** [comment]
Can you swap registration and validation flags to follow alphabetical sorting? The rest looks fine.

**Comment by dpeckett** [comment]
Thanks, updated.

**Comment by FxKu** [comment]
Ah two more missing pieces.
1. We use to copy the OperatorConfiguration into an internal config struct. You need to add this new option [here](https://github.com/zalando/postgres-operator/blob/b4155bc8fb468590677fb1e808708884d744d694/pkg/controller/operator_config.go#L35).

2. Can you update code generation (`make codegen`) and commit the changed pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go file?

**Comment by FxKu** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:

**Comment by ant31** [comment]
awesome, thank you @dpeckett

**Pull request merged**
