### PR TITLE
fix statefulset sync

### PR DESCRIPTION
**Pull request by sdudoladov**
removes excessive syncing of stateful sets

### CODE REVIEW

**Comment by Jan-M** [comment]
How are we testing this in kind for example to make sure it is solving the problem?

**Comment by sdudoladov** [comment]
```bash
kind start cluster --name kind-m-2 --config ~/.kube/kind-config-multikind.yaml --loglevel debug
kind load docker-image "registry.opensource.zalan.do/acid/postgres-operator:v1.1.0-23-gf29bdaf-dirty" --name kind-m
# submit operator as in quickstart but with the new image version in the deployment
kubectl create -f manifests/minimal-postgres-manifest.yaml
```
restart the operator pod to force a SYNC and see how the unnecessary Sync does not happen

**Comment by sdudoladov** [comment]
:+1:

**Comment by FxKu** [comment]
:+1:

**Pull request merged**
