### PR TITLE
Fixing toleration fields requirements

### PR DESCRIPTION
**Pull request by preved911**
Hello. Tolerations subfileds aren't required in all cases. I think that required subfields list should be removed from crd.

### CODE REVIEW

**Comment by FxKu** [comment]
There is a third place you would have to remove it: https://github.com/zalando/postgres-operator/blob/fb8a6c7a6823bb143bbfd6b5ec2e75d8de4b40d9/pkg/apis/acid.zalan.do/v1/crds.go#L796

**Comment by preved911** [comment]
> There is a third place you would have to remove it

thanks, removed

**Comment by FxKu** [comment]
:+1:

**Comment by jopadi** [comment]
👍

**Comment by FxKu** [comment]
Thanks @preved911 for your contribution.

**Pull request merged**
