### PR TITLE
Fix (#2644) - Add json tags to InfrastructureRole struct

### PR DESCRIPTION
**Pull request by hemakshis**
Use `json` instead of `name` tags.

### CODE REVIEW

**Comment by FxKu** [comment]
May I ask you to rebase your branch to resolve the conflict and also test this with configuring via configmap?

**Comment by FxKu** [comment]
I mean configuring the operator with a [configmap](https://github.com/zalando/postgres-operator/blob/master/manifests/configmap.yaml) and put this setting in there:

```
infrastructure_roles_secrets: secretname:postgresql-infrastructure-roles,userkey:username,passwordkey:password,rolekey:roles
```

And in the deployment this configmap needs to be [referenced](https://github.com/zalando/postgres-operator/blob/master/manifests/postgres-operator.yaml#L38). Can you test this? Then we are good to go. Maybe you did and I've only misunderstood you.

**Comment by hemakshis** [comment]
With the configmap approach, it is always trying to look for the secret in the default namespace -

ConfigMap values -
```yaml
  infrastructure_roles_secret_name: postgresql-infrastructure-roles-oncall
  infrastructure_roles_secrets: "secretname:postgres-operator.postgresql-infrastructure-roles,userkey:username,passwordkey:password,rolekey:roles"
```

Logs -
```shell
time="2024-06-11T13:30:13Z" level=warning msg="could not get infrastructure roles: could not get infrastructure roles secret default/postgres-operator.postgresql-infrastructure-roles: secrets \"postgres-operator.postgresql-infrastructure-roles\" not found" pkg=controller
```

**Comment by FxKu** [comment]
Thanks @hemakshis for testing. LGTM then :smiley:

**Comment by FxKu** [comment]
:+1:

**Comment by idanovinda** [comment]
👍

**Pull request merged**
