### PR TITLE
postgres-operator deployment template: run operator as non-root, and with readonly filesystem

### PR DESCRIPTION
**Pull request by knan-nrk**
postgres-operator deployment template: 

Support running operator as non-root, and with readonly filesystem

[edit add description to content too]

### CODE REVIEW

**Comment by FxKu** [comment]
non-root is also covered by #531. You have to use a custom Spilo image though.

**Comment by knan-nrk** [comment]
Complementary. This is for the operator deployment/pod itself. #531 is for the statefulsets/pods created by the operator.

**Comment by FxKu** [comment]
Btw. does this PR close #560?
I'm thinking of putting these additions in comments and write a paragraph in the developer docs (maybe after https://github.com/zalando/postgres-operator/blob/master/docs/developer.md#deploying-self-build-image)?

**Comment by knan-nrk** [comment]
No, this is for the operator pod, #560 is for the spilo/database pods. So they are complementary but separate.

**Comment by Jan-M** [comment]
Looks good to me.

**Comment by Jan-M** [comment]
:+1:

**Comment by sdudoladov** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks @knan-nrk for this contribution!

**Pull request merged**
