### PR TITLE
Add pes to backupjob

### PR DESCRIPTION
**Pull request by robertlandrum**
Added support for the pod_environment_secret and pod_environment_configmap settings to the logical backup job to support credentials and custom S3 buckets per db.

### CODE REVIEW

**Comment by stgrace** [comment]
Duplicate of https://github.com/zalando/postgres-operator/pull/2051

**Comment by pierreyves-lebrun** [comment]
@Jan-M @sdudoladov @FxKu @idanovinda @hughcapet @jopadi please kindly review this pull request

**Review by yajo — CHANGES_REQUESTED** [review]
IMHO this secret should be in a separate config.

For example, in the `OperatorConfiguration`, add:

```yaml
configuration:
  logical_backup_env:
    # Normal env definition; see https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: accessKey
      # ...
```

The rationale is that I don't want to give access to those backup buckets to normal postgres pods, if that makes sense.

**Comment by stgrace** [comment]
See #2051

**Comment by FxKu** [comment]
Closing in favor for #2051. Better to have separate options and not reuse pod env vars.

**Pull request closed without merging**
