### PR TITLE
Add kustomize support to Postgres UI. (#1087)

### LINKED ISSUE #1087: Supply kustomize manifest for UI
It would be great if there was a kustomize in the manifest for the UI.

### PR DESCRIPTION
**Pull request by hoangelos**
closes #1087

### CODE REVIEW

**Comment by hoangelos** [comment]
Mentions how it fixes #1087

**Comment by FxKu** [comment]
:+1:

**Comment by RafiaSabih** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks again @hoangelos for your contribution!

**Pull request merged**
