### PR TITLE
Allow additional secret to be set in postgresql cr

### PR DESCRIPTION
**Pull request by muff1nman**

### CODE REVIEW

**Comment by FxKu** [comment]
To me it looks like this feature is already covered by [this](https://github.com/zalando/postgres-operator/pull/736) PR. Am I wrong?

**Comment by muff1nman** [comment]
Ah I missed that PR. However that PR needs some adjusting. Let me comment over there.

**Comment by ReSearchITEng** [comment]
just a note: #736 has been merged.

**Comment by FxKu** [comment]
I think we can close this one now. Feel free to reopen if you want to continue working on it and you use case isn't covered with `additionalVolumes`.

**Pull request closed without merging**
