### PR TITLE
Improve gcs docs

### PR DESCRIPTION
**Pull request by sagor999**
This adds documentation on how to make cloning work when using GCS.
It relies on this PR to be approved first: 
https://github.com/zalando/postgres-operator/pull/1176

### CODE REVIEW

**Comment by erthalion** [comment]
If it relies on #1176, why not move this change set into it?

**Comment by sagor999** [comment]
@erthalion I prefer not to bundle several changes together into one PR. But if you prefer, I can easily do that. Let me know.

**Comment by erthalion** [comment]
It's not a big deal I guess, but just in case I would ask you to pack the relevant changes together. It could be a separate commit to isolate stuff, but otherwise there is a chance to miss something. Does it sound good for you?

**Comment by sagor999** [comment]
@erthalion not a problem! I merged changes into https://github.com/zalando/postgres-operator/pull/1176 and closing this one.

**Pull request closed without merging**
