### PR TITLE
feat: [ui] Relative navigation; add storageClass

### PR DESCRIPTION
**Pull request by orangetcy**
- Change all ui request from absolute path to relative path.
  Can access ui web like ex.com/pgo/ with nginx spec config
  relative issue: zalando#1613

- Add storageClass field relative-nav

### CODE REVIEW

**Comment by Jordan-Queiroz** [comment]
Hello 😃

This is a a very important feature. I'm looking forward to it 😃 Do you have any plans for a release with this feature?

**Comment by idanovinda** [comment]
👍

**Comment by FxKu** [comment]
:+1:

**Comment by jopadi** [comment]
👍

**Pull request merged**
