### PR TITLE
fix(chart) update comments

### PR DESCRIPTION
**Pull request by holyhope**
Signed-off-by: Pierre Péronnet <pierre.peronnet@ovhcloud.com>

### CODE REVIEW

**Comment by FxKu** [comment]
Can you change it in the [values-crd.yaml](https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values-crd.yaml), too? Thanks :)

**Comment by holyhope** [comment]
Not sure why `operator-e2e-tests / End-2-End tests (pull_request) Failing after 15m — End-2-End tests` failed.

```
FAIL: test_node_affinity (test_e2e.EndToEndTestCase)
Add label to a node and update postgres cluster spec to deploy only on a node with that label
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/tests/test_e2e.py", line 1210, in test_node_affinity
    self.eventuallyEqual(lambda: self.k8s.get_operator_state(), {"0": "idle"}, "Operator does not get in sync")
  File "/tests/test_e2e.py", line 42, in eventuallyEqual
    self.assertEqual(y, x, m.format(y))
AssertionError: None != {'0': 'idle'} : Operator does not get in sync
```

please help @FxKu

**Comment by FxKu** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks @holyhope. Yeah, that test is known to be flaky, unfortunately. In our internal build/test pipeline there are no issues.

**Pull request merged**
