### PR TITLE
Fix bad formatting in docs

### PR DESCRIPTION
**Pull request by yujunz**
List requires a proceeding empty line

### CODE REVIEW

**Comment by RafiaSabih** [comment]
These changes look good. However, while you are on it, won't you like to correct similar issues in other parts of docs, I could find a few places in developer.md and user.md...

**Comment by yujunz** [comment]
>  I could find a few places in developer.md and user.md...

I haven't gone through all docs yet. Feel free to edit this PR for related amends.

**Comment by FxKu** [comment]
:+1:

**Comment by RafiaSabih** [comment]
:+1:

**Pull request merged**
