### PR TITLE
Add namespace to helm chart resources that need them

### LINKED ISSUE #1525: Helm: Chart not using helm-flag '--namespace'
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
  registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
  GKE
- **Are you running Postgres Operator in production?** [yes | no]
  Not yet
- **Type of issue?** [Bug report, question, feature request, etc.]
  Bug report/feature request

Here is a gist with the result and also the issued commands used to generate the output:
https://gist.github.com/flyinggecko/dc94f4bebf867dcd37d5fdadacb1efd7

As not everyone using helm and kubernetes with a set namespace per context, the resources will be added to the default namespace. This results in a broken installation of the operator.

If interested I'm willing to fix this, as it means manually going through the generated manifest, when updating the operator.

### PR DESCRIPTION
**Pull request by flyinggecko**
This fixes #1525.

### CODE REVIEW

**Comment by FxKu** [comment]
:+1:

**Comment by flyinggecko** [comment]
Hey, do I need to do anything to fix those e2e-tests? I'm not able to see any logs, so it would be hard for me to analyze them ;)

**Comment by RafiaSabih** [comment]
:+1:

**Comment by FxKu** [comment]
Thanks @flyinggecko for your contribution!

**Pull request merged**
