### PR TITLE
fix operator 1.7.0 helm package

### PR DESCRIPTION
**Pull request by FxKu**
updating the 1.7.0 helm chart with the latest fix from #1603

### CODE REVIEW

**Comment by FxKu** [comment]
:+1:

**Comment by RafiaSabih** [comment]
:+1:

**Comment by stanislav-zaprudskiy** [comment]
Thank you for the update! This would also be super-useful if you just increased the patch version instead of overwriting the existing version.

**Comment by david-l-riley** [comment]
^ this; not updating the patch version can cause a lot of caching problems with Helm. Once a version gets released, it shouldn't change.

**Pull request merged**
